name: setup-php
description: |
  Setup PHP with extensions

  See https://github.com/shivammathur/setup-php

inputs:
  php-version:
    description: 'Setup PHP version.'
    default: '7.4'
    required: false
  extensions:
    description: 'Setup PHP extensions.'
    required: false
  ini-values:
    description: 'Add values to php.ini.'
    required: false
  coverage:
    description: 'Setup code coverage driver.'
    required: false
  tools:
    description: 'Setup popular tools globally.'
    required: false
  cache-key:
    description: 'Cache key ex: v1'
    default: 'v1'
    required: false

runs:
  using: "composite"
  steps:
    - name: Exclude psr from extensions # https://github.com/shivammathur/setup-php/issues/799
      id: extensions
      shell: bash
      run: |
        if [[ -z "${{ inputs.extensions }}" ]]; then
          echo "php-extensions=:psr" >> "$GITHUB_OUTPUT"
        else
          echo "php-extensions=${{ inputs.extensions }},:psr" >> "$GITHUB_OUTPUT"
        fi

    - name: Setup cache environment
      id: extcache
      uses: shivammathur/cache-extensions@9b476298b44f2e4d4268dd103ff4c3e216314e27 # v1
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ steps.extensions.outputs.php-extensions }}
        key: ${{ inputs.cache-key }}

    - name: Cache extensions
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
      with:
        path: ${{ steps.extcache.outputs.dir }}
        key: ${{ steps.extcache.outputs.key }}
        restore-keys: ${{ steps.extcache.outputs.key }}

    - name: Setup PHP
      uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ steps.extensions.outputs.php-extensions }}
        ini-values: ${{ inputs.ini-values }}
        coverage: ${{ inputs.coverage }}
        tools: ${{ inputs.tools }}
